### ISSUE TITLE
Fix BlueAngelHost VPS Host Interactions 

### ISSUE THREAD

**Issue by andrebreis** [MattSkala/cloudomate#3]
VPS Hosters websites are constantly changing and cloudomate's current parser is outdated which makes it impossible to interact correctly with the website in order to acquire a VPS

**Comment by MattSkala** [comment]
Both `options` and `purchase` commands are now working for BlueAngelHost

**Comment by MattSkala** [comment]
Fetching server stats from the client area and e-mail parsing have been fixed, so `status`, `info`, and `getip` commands are now working properly.

**Comment by rpytel1** [comment]
Shall we close the issue?

**Comment by andrebreis** [comment]
Closed by #7
